setwd("C:/Users/d2i2k/tmp/RepData_PeerAssessment1")
ActivityData <- read.csv("activity.csv", header=TRUE) 
y <- tapply(ActivityData$steps,INDEX=ActivityData$interval,FUN=mean,na.rm=TRUE)
x <- tapply(ActivityData$interval,INDEX=ActivityData$interval,FUN=mean,na.rm=TRUE)
xy <- cbind(x,y)
plot(xy,type="l",main="Time Series of Mean Steps",xlab="Daily Interval (in minutes)",ylab="Average Number of Steps")
which.max(y)